"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { useDeferredValue, useRef, useState } from "react";
import { ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronRight, CircleAlert, Grid2X2, LayoutList, LockKeyhole, Plus, RotateCcw, Search, SlidersHorizontal, X } from "lucide-react";
import { artifactMarkdown, collections, publicCollection, stages, type Artifact, type Intake } from "@/lib/domain";
import { ArtifactEditor, IntakeForm } from "./curation-panel";
import { useArchive } from "./use-archive";

const ObjectScene = dynamic(() => import("./object-scene").then((module) => module.ObjectScene), { ssr: false, loading: () => <div className="scene-loading" role="status">Preparing object view...</div> });

export function Museum({ mode, initialArtifacts, initialError, projectId, generator }: { mode: "demo" | "live"; initialArtifacts: Artifact[]; initialError: string | null; projectId: string | null; generator: "model" | "template" }) {
  const archive = useArchive(mode, initialArtifacts, initialError);
  const [view, setView] = useState<"collection" | "curator" | "about">("collection");
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState("accession");
  const [layout, setLayout] = useState<"grid" | "list">("grid");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  const [code, setCode] = useState("");
  const [downloadNotice, setDownloadNotice] = useState("");
  const resetDialog = useRef<HTMLDialogElement>(null);
  const query = useDeferredValue(search).toLowerCase();
  const all = view === "curator" && archive.unlocked ? archive.artifacts : publicCollection(archive.artifacts);
  const objects = all.filter((artifact) => (filter === "all" || artifact.collectionId === filter) && `${artifact.title} ${artifact.material} ${artifact.kind}`.toLowerCase().includes(query)).sort((first, second) => sort === "strangeness" ? second.strangeness - first.strangeness : sort === "title" ? first.title.localeCompare(second.title) : first.accession.localeCompare(second.accession));
  const selected = all.find((artifact) => artifact._id === selectedId) || null;
  const exhibitedCount = publicCollection(archive.artifacts).length;

  function changeView(next: typeof view) { setView(next); setSelectedId(null); setAdding(false); setFilter("all"); setSearch(""); }
  function openArtifact(id: string) { setSelectedId(id); setDownloadNotice(""); window.scrollTo({ top: 0, behavior: "instant" }); }
  async function addArtifact(input: Intake) { const created = await archive.add(input); if (created) { setAdding(false); setFilter("all"); setSearch(""); openArtifact(created._id); } return created; }
  function download(artifact: Artifact) {
    const url = URL.createObjectURL(new Blob([artifactMarkdown(artifact)], { type: "text/markdown;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${artifact.accession.toLowerCase()}.md`; anchor.click(); URL.revokeObjectURL(url); setDownloadNotice("Catalogue record downloaded.");
  }

  return <div className="museum-shell">
    <header className="museum-header"><Link href="/" className="museum-brand" aria-label="Afterlight home"><span className="brand-symbol" aria-hidden="true">a<span>+</span></span><span>afterlight<small>THE EVERYDAY, RECONSIDERED.</small></span></Link><nav aria-label="Museum"><button type="button" className={view === "collection" ? "active" : ""} aria-current={view === "collection" ? "page" : undefined} onClick={() => changeView("collection")}>The collection<span>{exhibitedCount.toString().padStart(2, "0")}</span></button><button type="button" className={view === "curator" ? "active" : ""} aria-current={view === "curator" ? "page" : undefined} onClick={() => changeView("curator")}>Curator desk</button><button type="button" className={view === "about" ? "active" : ""} aria-current={view === "about" ? "page" : undefined} onClick={() => changeView("about")}>Archive notes</button></nav><div className="archive-mode"><span />{mode === "demo" ? "LOCAL DEMO" : "SANITY LIVE"}<small>{archive.connection}</small></div></header>
    <main id="main" className="museum-main">
      {archive.error && <div className="message error" role="alert"><CircleAlert size={17} aria-hidden="true" /><span>{archive.error}</span>{mode === "demo" && <button className="text-action" type="button" onClick={() => resetDialog.current?.showModal()}>Reset local archive</button>}</div>}
      {view === "about" ? <section className="archive-notes"><span className="eyebrow">A NOTE FROM THE ARCHIVE / 2126</span><h1>The extraordinary was<br />here all along.</h1><p className="notes-intro">A cassette. A key. A little glass bulb. Things so familiar that nobody thought to explain them.</p><div className="notes-body"><p>Afterlight is a fictional museum looking back at everyday objects from an imagined future. The physical observations are catalogued separately from the stories we invent around them. Every interpretation is speculative; these are original reconstructions, not photographs or historical evidence.</p><p>A draft is not an exhibit. A curator reviews the label before an object joins the collection. Returning it for revision takes it off display.</p><dl><div><dt>Archive mode</dt><dd>{mode === "demo" ? "Local browser demonstration" : "Sanity Content Lake"}</dd></div><div><dt>Sanity project</dt><dd>{projectId || "Not connected"}</dd></div><div><dt>Draft preparation</dt><dd>{mode === "live" && generator === "model" ? "AI-generated, human-reviewed" : "Deterministic sample template"}</dd></div><div><dt>Live writes verified</dt><dd>{mode === "demo" ? "Not applicable in local demo" : "Verify with a curator action and Studio"}</dd></div></dl><a href="https://dev.to/challenges/sanity-2026-09-16" target="_blank" rel="noreferrer" className="text-action">Sanity Challenge / Path Two<ArrowUpRight size={16} aria-hidden="true" /></a></div></section>
      : view === "curator" && !archive.unlocked ? <section className="unlock-view"><LockKeyhole size={32} aria-hidden="true" /><span className="eyebrow">CURATOR ACCESS</span><h1>The other side<br />of the label.</h1><form onSubmit={(event) => { event.preventDefault(); void archive.unlock(code); }}><label htmlFor="curator-code">Curator access code</label><input id="curator-code" type="password" autoComplete="off" required value={code} onChange={(event) => setCode(event.target.value)} /><button className="primary-command" type="submit" disabled={archive.pending}>Open curator desk<ArrowRight size={16} aria-hidden="true" /></button></form></section>
      : adding ? <IntakeForm pending={archive.pending} onAdd={addArtifact} onCancel={() => setAdding(false)} />
      : selected ? <>
        <div className="detail-breadcrumb"><button className="text-action" type="button" onClick={() => setSelectedId(null)}><ArrowLeft size={15} aria-hidden="true" />{view === "curator" ? "Curator desk" : "The collection"}</button><ChevronRight size={13} aria-hidden="true" /><span>{selected.accession}</span><button type="button" className="round-tool" title="Download catalogue record" aria-label="Download catalogue record" onClick={() => download(selected)}><ArrowDownToLine size={17} /></button></div>
        <section className="object-detail"><div className={`object-stage theme-${selected.collectionId}`}><div className="stage-index"><span>{selected.accession}</span><span>RECONSTRUCTION / {selected.kind.toUpperCase()}</span></div><Image className="stage-fallback" src={`/objects/${selected.kind}.png`} alt="" width={600} height={480} priority unoptimized /><ObjectScene key={selected._id} kind={selected.kind} /><span className="stage-watermark" aria-hidden="true">afterlight</span></div><div className="object-description"><span className="eyebrow">{collections.find((collection) => collection._id === selected.collectionId)?.title}</span><h1>{selected.title}</h1><p className="object-label">{selected.label || "This object is waiting for its first interpretation."}</p><dl className="object-facts"><div><dt>Material</dt><dd>{selected.material}</dd></div><div><dt>Strangeness</dt><dd><span className="strangeness-dots" aria-label={`${selected.strangeness} out of 5`}>{[1, 2, 3, 4, 5].map((level) => <span key={level} className={level <= selected.strangeness ? "filled" : ""} />)}</span></dd></div><div><dt>Status</dt><dd><span className={`stage-label stage-${selected.stage}`}>{selected.stage}</span></dd></div></dl><div className="object-note"><h2>What we can see</h2><p>{selected.observed}</p></div><div className="object-note interpretation-note"><h2>A possible story <span>FICTION</span></h2><p>{selected.interpretation || "Not yet drafted."}</p></div></div></section>
        {view === "curator" && <ArtifactEditor key={selected._id} artifact={selected} pending={archive.pending} generator={mode === "demo" ? "template" : generator} operate={(operation) => archive.operation(selected._id, operation)} />}
      </> : <>
        <section className="collection-heading"><div><span className="eyebrow">{view === "collection" ? "A FICTIONAL MUSEUM OF ORDINARY THINGS / EST. 2126" : "WORK IN PROGRESS / THE CURATOR DESK"}</span><h1>{view === "collection" ? <>Small things.<br /><em>Long afterlives.</em></> : <>Behind every object,<br /><em>a second look.</em></>}</h1></div><div className="collection-heading-side">{view === "collection" ? <><span className="issue-number">01<span>/</span></span><p>THE FIRST COLLECTION</p><span className="collection-date">Objects from the near past.</span></> : <><button className="primary-command" type="button" onClick={() => setAdding(true)} disabled={!archive.ready || archive.pending}><Plus size={17} aria-hidden="true" />New object</button><span className="collection-date">{archive.artifacts.length} objects in the archive</span></>}</div></section>
        {view === "curator" && <div className="workflow-summary" aria-label="Workflow counts">{stages.map((stage, index) => <div key={stage}><span className="workflow-number">0{index + 1}</span><strong>{stage}</strong><span className="workflow-count">{archive.artifacts.filter((artifact) => artifact.stage === stage).length}</span>{index !== stages.length - 1 && <ArrowRight size={15} aria-hidden="true" />}</div>)}</div>}
        <div className="collection-toolbar"><div className="collection-filters" role="group" aria-label="Collection filter"><button type="button" aria-pressed={filter === "all"} className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All objects<span>{all.length}</span></button>{collections.map((collection) => <button type="button" key={collection._id} aria-pressed={filter === collection._id} className={filter === collection._id ? "active" : ""} onClick={() => setFilter(collection._id)}>{collection.title}</button>)}</div><div className="display-controls"><label className="sort-control"><SlidersHorizontal size={15} aria-hidden="true" /><span className="sr-only">Sort objects</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="accession">Archive order</option><option value="title">Title</option><option value="strangeness">Strangeness</option></select></label><div className="layout-switch" role="group" aria-label="Collection layout"><button type="button" title="Grid view" aria-label="Grid view" aria-pressed={layout === "grid"} className={layout === "grid" ? "active" : ""} onClick={() => setLayout("grid")}><Grid2X2 size={17} /></button><button type="button" title="List view" aria-label="List view" aria-pressed={layout === "list"} className={layout === "list" ? "active" : ""} onClick={() => setLayout("list")}><LayoutList size={18} /></button></div></div></div>
        <div className="collection-search-row"><span className="eyebrow">{objects.length.toString().padStart(2, "0")} OBJECTS / {filter === "all" ? "ALL COLLECTIONS" : collections.find((collection) => collection._id === filter)?.title.toUpperCase()}</span><label className="collection-search"><Search size={15} aria-hidden="true" /><span className="sr-only">Search objects</span><input type="search" placeholder="Find an object" value={search} onChange={(event) => setSearch(event.target.value)} /></label></div>
        <section className={`object-grid ${layout === "list" ? "object-list" : ""}`} aria-label="Objects">{objects.map((artifact) => <article className="object-card" key={artifact._id}><button type="button" className="object-open" onClick={() => openArtifact(artifact._id)} aria-label={`Inspect ${artifact.title}`}><div className={`object-image theme-${artifact.collectionId}`}><span className="object-accession">{artifact.accession}</span>{view === "curator" && <span className={`stage-label stage-${artifact.stage}`}>{artifact.stage}</span>}<Image src={`/objects/${artifact.kind}.png`} alt={`Original 3D reconstruction of a ${artifact.kind}`} width={600} height={480} unoptimized /><span className="inspect-object"><Plus size={18} aria-hidden="true" /></span></div><div className="object-card-caption"><span className="eyebrow">{collections.find((collection) => collection._id === artifact.collectionId)?.title}</span><h2>{artifact.title}</h2><div className="object-card-meta"><span>{artifact.kind.toUpperCase()}</span><span className="strangeness-dots" aria-label={`Strangeness ${artifact.strangeness} of 5`}>{[1, 2, 3, 4, 5].map((level) => <span className={level <= artifact.strangeness ? "filled" : ""} key={level} />)}</span><ArrowUpRight size={16} aria-hidden="true" /></div></div></button></article>)}</section>
        {objects.length === 0 && <div className="empty-collection"><Search size={28} aria-hidden="true" /><h2>No objects here. Yet.</h2><button className="text-action" type="button" onClick={() => { setFilter("all"); setSearch(""); }}>Clear filters <X size={14} aria-hidden="true" /></button></div>}
        <section className="archive-colophon"><span className="colophon-mark" aria-hidden="true">a+</span><div><span className="eyebrow">THE EVERYDAY, RECONSIDERED.</span><p>Some things outlast<br />their explanations.</p></div><button type="button" className="text-action" onClick={() => changeView("about")}>A note from the archive<ArrowUpRight size={16} aria-hidden="true" /></button></section>
      </>}
      <p className="archive-notification" role="status" aria-live="polite">{archive.notice || downloadNotice}</p>
    </main>
    <footer className="museum-footer"><span>AFTERLIGHT <span className="footer-divider">/</span> A FICTIONAL ARCHIVE</span><span>Made with Sanity. Kept with care.</span><div><span className="footer-dot" />{mode === "demo" ? "Local demonstration" : "Sanity Content Lake"}{mode === "demo" && <button type="button" title="Reset local archive" aria-label="Reset local archive" disabled={archive.pending} onClick={() => resetDialog.current?.showModal()}><RotateCcw size={14} /></button>}</div></footer>
    <dialog className="reset-dialog" ref={resetDialog} aria-labelledby="reset-title"><div className="dialog-heading"><h2 id="reset-title">Reset the local archive?</h2><button type="button" className="round-tool" title="Close dialog" aria-label="Close dialog" onClick={() => resetDialog.current?.close()}><X size={18} /></button></div><p>Your local edits and new objects will be removed. This does not change any Sanity dataset.</p><div className="dialog-actions"><button type="button" className="secondary-command" onClick={() => resetDialog.current?.close()}>Cancel</button><button type="button" className="primary-command" onClick={() => { archive.resetDemo(); setSelectedId(null); setAdding(false); resetDialog.current?.close(); }}><Check size={16} aria-hidden="true" />Reset demo</button></div></dialog>
  </div>;
}