#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
set +x
umask 077
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE="$PWD/.env.local"
[[ -t 0 ]] || { warn "Run this wizard directly in your own terminal."; exit 1; }
[[ ! -L "$ENV_FILE" ]] || { warn "Refusing to overwrite a symlinked environment file."; exit 1; }
node -e 'process.exit(Number(process.versions.node.split(".")[0]) === 24 ? 0 : 1)' || { warn "Activate Node.js 24 before running this wizard."; exit 1; }

capture_secret() {
  local key="$1" prompt="$2" value
  while true; do
    ask_secret "$key" "$prompt"
    value="${!key}"
    if [[ -n "$value" && "$value" != *[[:space:]]* && "$value" != *\#* && "$value" != *\"* && "$value" != *\'* && "$value" != *\\* ]]; then
      write_env "$key" "$value"
      export "$key"
      return
    fi
    warn "Enter a non-empty credential without whitespace, quotes, backslashes, or #. Its value will not be printed."
  done
}

banner "Afterlight: configure actual Sanity persistence and model drafting"
say "This configures only this project's environment and the Sanity project you choose."
say "No public deployment, Git push, or DEV publication is performed."
confirm "Proceed, keeping local demo mode until the final activation stage?" || exit 0
write_env APP_MODE demo

stage "Create or select the Path Two project"
open_url "https://www.sanity.io/manage"
step "Create or select a separate Afterlight project. Use a PRIVATE production dataset to protect unpublished workflow content."
ask SANITY_STUDIO_PROJECT_ID "Project ID:"
[[ "$SANITY_STUDIO_PROJECT_ID" =~ ^[a-z0-9]+$ ]] || { warn "The project ID must contain lowercase letters and digits."; exit 1; }
ask SANITY_STUDIO_DATASET "Dataset name [production]:"
SANITY_STUDIO_DATASET="${SANITY_STUDIO_DATASET:-production}"
[[ "$SANITY_STUDIO_DATASET" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || { warn "Invalid dataset name."; exit 1; }
write_env SANITY_STUDIO_PROJECT_ID "$SANITY_STUDIO_PROJECT_ID"
write_env SANITY_STUDIO_DATASET "$SANITY_STUDIO_DATASET"
export SANITY_STUDIO_PROJECT_ID SANITY_STUDIO_DATASET

stage "Project read and write tokens"
open_url "https://www.sanity.io/manage"
step "Select the Afterlight project, then API > Tokens. Create a Viewer token for server reads and an Editor token for workflow mutations."
capture_secret SANITY_READ_TOKEN "Project Viewer token (hidden):"
capture_secret SANITY_WRITE_TOKEN "Project Editor token (hidden):"
note "Both tokens stay on the server. Never provide them as a curator login code."

stage "Real model drafting and curator access"
open_url "https://aistudio.google.com/app/apikey"
step "Use a Gemini API key from your own Google AI Studio project and review its quota and billing settings."
capture_secret GOOGLE_GENERATIVE_AI_API_KEY "Gemini API key (hidden):"
ask GOOGLE_MODEL "Model ID [gemini-3.5-flash-lite]:"
GOOGLE_MODEL="${GOOGLE_MODEL:-gemini-3.5-flash-lite}"
[[ "$GOOGLE_MODEL" =~ ^[a-zA-Z0-9._:-]+$ ]] || { warn "Enter a model ID, not a URL or command."; exit 1; }
write_env GOOGLE_MODEL "$GOOGLE_MODEL"
export GOOGLE_MODEL
ask_secret CURATOR_ACCESS_CODE "Curator code, 24+ characters (Enter generates a private random code):"
CURATOR_ACCESS_CODE="${CURATOR_ACCESS_CODE:-$(node -p 'require("node:crypto").randomBytes(24).toString("hex")')}"
[[ ${#CURATOR_ACCESS_CODE} -ge 24 && "$CURATOR_ACCESS_CODE" =~ ^[a-zA-Z0-9_-]+$ ]] || { warn "Use at least 24 letters, digits, underscores, or hyphens for this code."; exit 1; }
write_env CURATOR_ACCESS_CODE "$CURATOR_ACCESS_CODE"
export CURATOR_ACCESS_CODE
note "The app-only code is stored privately in .env.local. Sample-template drafting remains demo-only."

stage "Seed the archive and deploy its schema"
say "This adds 3 collections and 8 objects without replacing existing records."
confirm "Write the seed records and deploy the schema to the selected project?" || exit 0
[[ -d node_modules ]] || npm ci
npm run seed
step "Authenticate the Sanity CLI in your own browser for schema deployment."
npx sanity login
npm run sanity:schema

stage "Activate the local live application"
ask APP_URL "Application origin [http://127.0.0.1:3002]:"
APP_URL="${APP_URL:-http://127.0.0.1:3002}"
write_env APP_URL "$APP_URL"
export APP_URL
confirm "Switch this project's local configuration to live mode?" || exit 0
write_env APP_MODE live
export APP_MODE=live
npm run doctor
say "Restart the Path Two server in its own terminal, then reload the browser."
say "If no server is running, start npm run dev -- --port 3002 in another terminal."
pause "Press Enter after the live application is running at APP_URL."
open_url "$APP_URL"

stage "Verify real persistence and drafting"
npm run check:live
if confirm "Run live acceptance? This uses model quota and briefly exhibits one temporary test object before withdrawing and deleting it."; then
  npm run check:live -- --exercise
else
  SKIPPED+=("Live workflow acceptance not run. Execute npm run check:live -- --exercise before submission.")
fi
step "Open this application in two browsers. Use the app-only curator code in the curator view."
step "Approve an object in one browser and check the public collection updates in the other."
step "Check the same record, revision, stage, and history in Studio. Do not claim a live event test passed before observing it."
SKIPPED+=("Record the live browser-refresh result; the automated HTTP check does not verify SSE delivery.")
SKIPPED+=("Deploy separately, configure hosted secrets and rate limits, and repeat acceptance against the hosted APP_URL.")
finish
warn "Configuration is not publication. Add the real project ID and verified live results to your Path Two DEV post."
